"""Seed script for themes - run from backend/ directory with: python seed_themes.py"""
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from config.database import SessionLocal, engine
from models.theme import ThemeSettings

def seed_themes():
    db = SessionLocal()
    try:
        # Check if themes already exist (other than default)
        existing_count = db.query(ThemeSettings).count()
        if existing_count > 6:  # Increased count check
            print("Themes already seeded. Skipping.")
            return

        themes = [
            {
                "name": "Midnight Pro",
                "is_active": False,
                "is_dark_mode": True,
                "primary_color": "#3b82f6",
                "secondary_color": "#1d4ed8",
                "accent_color": "#60a5fa",
                "background_color": "#0f172a",
                "surface_color": "#1e293b",
                "header_color": "#0f172a",
                "footer_color": "#0f172a",
                "text_primary_color": "#f8fafc",
                "text_secondary_color": "#94a3b8",
                "button_bg_color": "#3b82f6",
                "button_text_color": "#ffffff",
                "success_color": "#10b981",
                "warning_color": "#f59e0b",
                "error_color": "#ef4444",
                "border_color": "#334155",
                "font_family": "'Inter', sans-serif",
                "heading_font_size": "2.5rem",
                "body_font_size": "1rem",
                "font_weight": "400",
                "line_height": "1.6",
                "container_width": "1280px",
                "grid_columns": 4,
                "card_style": "rounded-2xl",
                "border_radius": "1rem",
                "box_shadow": "0 10px 15px -3px rgba(0, 0, 0, 0.3)",
                "section_spacing": "5rem",
                "header_height": "4.5rem",
                "footer_height": "auto",
                "button_border_radius": "0.75rem",
                "button_padding": "0.875rem 1.75rem",
                "button_hover_color": "#2563eb",
                "button_hover_animation": "scale-up",
                "button_shadow": "0 4px 6px -1px rgba(0, 0, 0, 0.2)"
            },
            {
                "name": "Nature Fresh",
                "is_active": False,
                "is_dark_mode": False,
                "primary_color": "#059669",
                "secondary_color": "#047857",
                "accent_color": "#34d399",
                "background_color": "#f0fdf4",
                "surface_color": "#ffffff",
                "header_color": "#064e3b",
                "footer_color": "#064e3b",
                "text_primary_color": "#064e3b",
                "text_secondary_color": "#374151",
                "button_bg_color": "#059669",
                "button_text_color": "#ffffff",
                "success_color": "#10b981",
                "warning_color": "#f59e0b",
                "error_color": "#ef4444",
                "border_color": "#dcfce7",
                "font_family": "'Outfit', sans-serif",
                "heading_font_size": "2.75rem",
                "body_font_size": "1.05rem",
                "font_weight": "400",
                "line_height": "1.7",
                "container_width": "1200px",
                "grid_columns": 4,
                "card_style": "rounded-3xl",
                "border_radius": "1.5rem",
                "box_shadow": "0 4px 20px -2px rgba(5, 150, 105, 0.1)",
                "section_spacing": "6rem",
                "header_height": "5rem",
                "footer_height": "auto",
                "button_border_radius": "2rem",
                "button_padding": "1rem 2rem",
                "button_hover_color": "#047857",
                "button_hover_animation": "bounce",
                "button_shadow": "0 10px 15px -3px rgba(5, 150, 105, 0.2)"
            },
            {
                "name": "Sunset Glow",
                "is_active": False,
                "is_dark_mode": False,
                "primary_color": "#f97316",
                "secondary_color": "#ea580c",
                "accent_color": "#fb923c",
                "background_color": "#fff7ed",
                "surface_color": "#ffffff",
                "header_color": "#431407",
                "footer_color": "#431407",
                "text_primary_color": "#431407",
                "text_secondary_color": "#713f12",
                "button_bg_color": "#f97316",
                "button_text_color": "#ffffff",
                "success_color": "#10b981",
                "warning_color": "#f59e0b",
                "error_color": "#ef4444",
                "border_color": "#ffedd5",
                "font_family": "'Plus Jakarta Sans', sans-serif",
                "heading_font_size": "2.5rem",
                "body_font_size": "1rem",
                "font_weight": "500",
                "line_height": "1.5",
                "container_width": "1440px",
                "grid_columns": 5,
                "card_style": "rounded-none",
                "border_radius": "0px",
                "box_shadow": "5px 5px 0px rgba(249, 115, 22, 0.2)",
                "section_spacing": "4rem",
                "header_height": "4rem",
                "footer_height": "auto",
                "button_border_radius": "0px",
                "button_padding": "0.75rem 2rem",
                "button_hover_color": "#ea580c",
                "button_hover_animation": "slide",
                "button_shadow": "4px 4px 0px #431407"
            },
            {
                "name": "Ocean Breeze",
                "is_active": False,
                "is_dark_mode": False,
                "primary_color": "#0891b2",
                "secondary_color": "#0e7490",
                "accent_color": "#22d3ee",
                "background_color": "#f0f9ff",
                "surface_color": "#ffffff",
                "header_color": "#083344",
                "footer_color": "#083344",
                "text_primary_color": "#083344",
                "text_secondary_color": "#334155",
                "button_bg_color": "#0891b2",
                "button_text_color": "#ffffff",
                "success_color": "#10b981",
                "warning_color": "#f59e0b",
                "error_color": "#ef4444",
                "border_color": "#e0f2fe",
                "font_family": "'DM Sans', sans-serif",
                "heading_font_size": "3rem",
                "body_font_size": "1.1rem",
                "font_weight": "400",
                "line_height": "1.6",
                "container_width": "1100px",
                "grid_columns": 3,
                "card_style": "rounded-lg",
                "border_radius": "0.5rem",
                "box_shadow": "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
                "section_spacing": "5rem",
                "header_height": "4rem",
                "footer_height": "auto",
                "button_border_radius": "0.5rem",
                "button_padding": "0.75rem 1.5rem",
                "button_hover_color": "#0e7490",
                "button_hover_animation": "fade",
                "button_shadow": "none"
            },
            {
                "name": "Pink Blossom",
                "is_active": False,
                "is_dark_mode": False,
                "primary_color": "#ec4899",
                "secondary_color": "#be185d",
                "accent_color": "#fbcfe8",
                "background_color": "#fff1f2",
                "surface_color": "#ffffff",
                "header_color": "#831843",
                "footer_color": "#831843",
                "text_primary_color": "#831843",
                "text_secondary_color": "#be185d",
                "button_bg_color": "#ec4899",
                "button_text_color": "#ffffff",
                "success_color": "#10b981",
                "warning_color": "#f59e0b",
                "error_color": "#ef4444",
                "border_color": "#ffe4e6",
                "font_family": "'Plus Jakarta Sans', sans-serif",
                "heading_font_size": "2.5rem",
                "body_font_size": "1rem",
                "font_weight": "400",
                "line_height": "1.6",
                "container_width": "1280px",
                "grid_columns": 4,
                "card_style": "rounded-2xl",
                "border_radius": "1rem",
                "box_shadow": "0 10px 15px -3px rgba(236, 72, 153, 0.1)",
                "section_spacing": "5rem",
                "header_height": "4.5rem",
                "footer_height": "auto",
                "button_border_radius": "9999px",
                "button_padding": "0.875rem 2rem",
                "button_hover_color": "#db2777",
                "button_hover_animation": "scale",
                "button_shadow": "0 4px 6px -1px rgba(236, 72, 153, 0.3)"
            },
            {
                "name": "Royal Purple",
                "is_active": False,
                "is_dark_mode": True,
                "primary_color": "#7c3aed",
                "secondary_color": "#6d28d9",
                "accent_color": "#a78bfa",
                "background_color": "#111827",
                "surface_color": "#1f2937",
                "header_color": "#0f172a",
                "footer_color": "#0f172a",
                "text_primary_color": "#f9fafb",
                "text_secondary_color": "#cbd5e1",
                "button_bg_color": "#7c3aed",
                "button_text_color": "#ffffff",
                "success_color": "#10b981",
                "warning_color": "#f59e0b",
                "error_color": "#ef4444",
                "border_color": "#374151",
                "font_family": "'Poppins', sans-serif",
                "heading_font_size": "2.75rem",
                "body_font_size": "1rem",
                "font_weight": "500",
                "line_height": "1.6",
                "container_width": "1280px",
                "grid_columns": 4,
                "card_style": "glassmorphism",
                "border_radius": "1rem",
                "box_shadow": "0 8px 32px rgba(124, 58, 237, 0.25)",
                "section_spacing": "5rem",
                "header_height": "4.5rem",
                "footer_height": "auto",
                "button_border_radius": "0.75rem",
                "button_padding": "0.875rem 1.75rem",
                "button_hover_color": "#6d28d9",
                "button_hover_animation": "glow",
                "button_shadow": "0 4px 20px rgba(124, 58, 237, 0.4)"
            },
            {
                "name": "Luxury Gold",
                "is_active": False,
                "is_dark_mode": False,
                "primary_color": "#d4af37",
                "secondary_color": "#b8860b",
                "accent_color": "#f4d03f",
                "background_color": "#fdfcf8",
                "surface_color": "#ffffff",
                "header_color": "#1f2937",
                "footer_color": "#1f2937",
                "text_primary_color": "#111827",
                "text_secondary_color": "#4b5563",
                "button_bg_color": "#d4af37",
                "button_text_color": "#ffffff",
                "success_color": "#10b981",
                "warning_color": "#f59e0b",
                "error_color": "#ef4444",
                "border_color": "#f3e8c8",
                "font_family": "'Playfair Display', serif",
                "heading_font_size": "3rem",
                "body_font_size": "1.05rem",
                "font_weight": "400",
                "line_height": "1.8",
                "container_width": "1400px",
                "grid_columns": 4,
                "card_style": "elegant",
                "border_radius": "0.75rem",
                "box_shadow": "0 10px 30px rgba(212, 175, 55, 0.15)",
                "section_spacing": "6rem",
                "header_height": "5rem",
                "footer_height": "auto",
                "button_border_radius": "9999px",
                "button_padding": "1rem 2.5rem",
                "button_hover_color": "#b8860b",
                "button_hover_animation": "lift",
                "button_shadow": "0 6px 20px rgba(212, 175, 55, 0.3)"
            }
        ]

        for t_data in themes:
            theme = ThemeSettings(**t_data)
            db.add(theme)
        
        db.commit()
        print(f"Successfully seeded {len(themes)} new themes!")

    except Exception as e:
        db.rollback()
        print(f"Error seeding themes: {e}")
    finally:
        db.close()

if __name__ == "__main__":
    seed_themes()
